name: example
description: example for vimium
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0-238.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  vimium:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg

  # To add custom fonts to your application, add a fonts section here:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
