name: vimium
description: "Type-to-click like in vimium"
version: 0.0.1
homepage: https://github.com/ltOgt/vimium
publish_to: "none"

environment:
  sdk: ">=3.3.0-238.0.dev <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
